### ISSUE TITLE
[Bug]: Wrong arch detection

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using `Komac new`. Komac did not prompt for arch but incorrectly detected it:
![image](https://user-images.githubusercontent.com/56180050/221343680-c94d08d3-2d55-40ff-928b-bfb937d084d4.png)

**Comment by russellbanks** [comment]
Komac priorities the architecture in the url over what it detects, but this had only been for updating, not new. Will be fixed in next commit
