### ISSUE TITLE
[Bug]: Error when creating new packages with `Komac new`

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I can't add new packages with Komac. Test with `Test.Package`:
![image](https://user-images.githubusercontent.com/56180050/227710176-07ee11de-7587-4536-923e-9b1694d94965.png)

**Comment by russellbanks** [comment]
Thanks for reporting - I noticed this yesterday but thought it was because GitHub's servers were down because I was having trouble with their [expired certificate](https://www.githubstatus.com/incidents/x7njwb481j9b). I'll look into this now.
