### ISSUE TITLE
[Bug]: Failed to create pull request

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/coreybutler/nvm-windows/actions/runs/4685243965/jobs/8313882263#step:2:94

```
Found forked winget-pkgs repository: coreybutler/winget-pkgs
  Failed to create pull request
  node:internal/errors:841
    const err = new Error(message);
                ^
  
  Error: Command failed: & $env:JAVA_HOME_17_X64\bin\java.exe -jar komac.jar update --id 'CoreyButler.NVMforWindows' --version 1.1.11 --urls 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe' --submit
      at checkExecSyncError (node:child_process:828:11)
      at execSync (node:child_process:899:15)
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:77:39
      at processTicksAndRejections (node:internal/process/task_queues:[96](https://github.com/coreybutler/nvm-windows/actions/runs/4685243965/jobs/8313882263#step:2:97):5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 2592,
    stdout: null,
    stderr: null
  }
```

**Comment by russellbanks** [comment]
I'm not too sure on the reason here - I'm thinking it could be a one-time issue and running it again should fix it, but the error isn't too helpful so I'm making it have the reason in the next update

**Comment by russellbanks** [comment]
I'll also add some retry logic so that if this were to happen again, we could (unless GitHub's servers were down or something) rule out that it needed to be ran again.

**Comment by sitiom** [comment]
> I'm thinking it could be a one-time issue and running it again should fix it, but the error isn't too helpful so I'm adding more information to it in the next update

That was already the 4th attempt. Manually running the command on my machine worked though.

**Comment by crsib** [comment]
The same happens to Audacity now https://github.com/audacity/audacity/actions/runs/4786981931/jobs/8512358422

**Comment by russellbanks** [comment]
Thanks @crsib - I've added reasoning to the error and retry logic in 1.5.0 that I will release later.

**Comment by vedantmgoyal2009** [comment]
Although it has been defined in the message to show the reason, it is never displayed. Any clue @russellbanks?

- https://github.com/audacity/audacity/actions/runs/4786981931/jobs/8512358422
- https://github.com/electerm/electerm/actions/runs/4625867508/jobs/8256656137

https://github.com/russellbanks/Komac/blob/2d92db680c29ee43a2a6c085d8a34ec36dd736c4/src/main/kotlin/data/GitHubImpl.kt#L170-L173

**Comment by russellbanks** [comment]
> Although it has been defined in the message to show the reason, it is never displayed. Any clue @russellbanks?

Both those jobs were created with Komac 1.4.1. The error reasoning was added in 1.5.0

**Comment by sitiom** [comment]
This build job "failed" but actually was able to make a pull request:
https://github.com/dandavison/delta/actions/runs/5160535447/jobs/9296725451
https://github.com/microsoft/winget-pkgs/pull/108812
