### ISSUE TITLE
[Feature/Idea]: Komac should warn/avoid creating invalid manifests

### ISSUE THREAD

**Issue by superusercode** [russellbanks/Komac#201]
### What would you like to see changed/added?

There are a couple specific cases where komac generates invalid manifests when updating currently:
- Github Release release notes uses a lot of colons and other weird formatting, and gets copied to the release notes field verbatim.
  - https://github.com/microsoft/winget-pkgs/pull/107175/commits/3fe3d9fcfd9ee4e5da7973d89bb2b30e6a010fcc
- Manifest has a somewhat complicated mix of user scopes and flags as its installation options, and komac simplifies them incorrectly despite distinguishing between the scopes in the update dialogue.
  - https://github.com/microsoft/winget-pkgs/pull/107083/commits/f9fb7fa0d51748e4e762c47188f5be6ab451ed37
  - vs original matrix here https://github.com/microsoft/winget-pkgs/pull/107088/files
- Accidentally using the same architecture twice (and having no other differences between the two versions).
  - https://github.com/microsoft/winget-pkgs/pull/107261/commits/0b3397548cf4ad2c58f38db29e404cfda7066fbf
- Doesn't update product code if it explicitly matches the manifest the updater used to build the new one
  - https://github.com/microsoft/winget-pkgs/pull/107083/commits/f9fb7fa0d51748e4e762c47188f5be6ab451ed37

**Comment by russellbanks** [comment]
Thanks for reporting! These are all things that can be fixed - I'll address them individually as I work on them

**Comment by russellbanks** [comment]
The release notes do get formatted lots in [GitHubExtensions.kt](https://github.com/russellbanks/Komac/blob/main/src/main/kotlin/extensions/GitHubExtensions.kt) as Komac receives it from GitHub in Markdown/HTML. Those release notes are a little odd in the sense of emojis and zalgo text but in terms of making it plain for a manifest, it's what I'd expect. How do you think it should be different/better?

**Comment by russellbanks** [comment]
I've added updating for the product code version number

**Comment by vedantmgoyal2009** [comment]
> ![image](https://user-images.githubusercontent.com/60588434/239663857-b898a898-9573-4b22-b938-7cdfefb3b809.png) another edge case: versions with spaces in them cannot be uploaded by komac itself, though the write option works fine

Ohkay, so this is the bug that fails some of the winget-releaser runs but we were unable to get the root cause till now. Thanks @superusercode

**Comment by russellbanks** [comment]
> > How do you think it should be different/better?
> 
> I think if it's detected as causing the manifest to break then it shouldn't be included. The submitter will have to step in either way to adjust it and put it in right.

It doesn't look like that's what caused the pipelines to fail; it would have just needed re-running. The pipelines have a lot of one-off issues like that
