### ISSUE TITLE
[Bug]: `komac new` if you don't fill some of the optional fields at the start komac will abruptly stop without error

### ISSUE THREAD

**Issue by superusercode** [russellbanks/Komac#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[Recording 2023-05-21 114924.webm](https://github.com/russellbanks/Komac/assets/60588434/9edde82d-3467-411a-ba04-87d3a9e3ab1c)
This can be worked around by filling all optional fields up to this point and then just saving the manifest locally to manually delete anything unnecessary. I've had this happen with packages of any InstallerType, so I think the cause is that there is a required field that is not labeled as required.
Additionally the scope and upgradebehavior dialogues do not have the [Confirm] button to skip them.

**Comment by russellbanks** [comment]
Initially, this looks like the checkbox menu always expecting an input.

The Scope and UpgradeBehaviour both have defaults. The defaults for them are automatically selected so it's optional in the sense of not needing to think about it

**Comment by russellbanks** [comment]
The issue was if a prompt returns null, it's considered a Ctrl+C press and Komac should exit. If no items are selected in a Checkbox menu, it was returning null rather than an empty list.
