### ISSUE TITLE
[Bug]: Komac not on path after "winget install komac"?

### ISSUE THREAD

**Issue by kriswilk** [russellbanks/Komac#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed Komac using WinGet:

`winget install komac`

However, it wasn't added to PATH. I must navigate to

`C:\Users\<username>\AppData\Local\Komac\`

in order to run it.

Is this the expected behaviour of the installer?

**Comment by ifurther** [comment]
The new version is resolved.
