### ISSUE TITLE
[Feature/Idea]: The DMG created with jpackage does not include apple silicon support

### ISSUE THREAD

**Issue by superusercode** [russellbanks/Komac#217]
### What would you like to see changed/added?

Trying to run it after install starts the rosetta install prompt, where it can already be run natively with just the jar.

**Comment by russellbanks** [comment]
Without paying for a certificate for Komac, JPackage is the easiest tool I can use ([Conveyor](https://conveyor.hydraulic.dev) would have been an alternative). There isn't any cross-complication with JPackage so I build it using GitHub runners. It will depend on https://github.com/github/roadmap/issues/528 as you've said.
