### ISSUE TITLE
[Feature/Idea]: Add Submit Package Button.

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [russellbanks/Komac#231]
### What would you like to see changed/added?

Missing submit package button because some of the app have display version entries.

**Comment by russellbanks** [comment]
Could you explain a bit more of what you mean here? Komac has a submit option (or parameter) after creating a manifest.

**Comment by BrandonWanHuanSheng** [comment]
I think the AppsandFeaturesVersion DisplayVersion did not change by default. It will cause PR to validation failure https://github.com/microsoft/winget-pkgs/labels/Manifest-AppsandFeaturesVersion-Error. Supposed, they need to change the display version by updating the manifest. But it did not give me to change the Display Version Entries.

**Comment by russellbanks** [comment]
Have you got an example PR I can look at for this?

**Comment by BrandonWanHuanSheng** [comment]
I point to https://github.com/microsoft/winget-pkgs/blob/master/manifests/z/Zoom/Zoom/5.15.2.18096/Zoom.Zoom.installer.yaml#L62

**Comment by Pckgrapp** [comment]
I experienced this issue creating the new update for Zoom. Komac does not modify the displayversion.

**Comment by Dragon1573** [comment]
> Komac has a submit option (or parameter) after creating a manifest.

@russellbanks I just switch from `wingetcreate.exe` to `komac.exe`. I usually skip the automatic pull request action after creating or updating a manifest. Testing them in Windows Sandbox using `Tools/SandboxTest.ps1` and then create PR with `wingetcreate submit`. Does `komac.exe` provide such subcommands for creating PRs using already presented manifest directory? Thank you!
