### ISSUE TITLE
[Feature/Idea]: Support for System Proxy

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#247]
### What would you like to see changed/added?

In some areas like China mainland, we often need proxy to access Github. Because Github in these areas is not available or very slow
**I've noticed that Komac didn't use system proxy even though I enabled global proxy**

**Comment by russellbanks** [comment]
Could you try using the JAR and checking whether your proxy works with `-Djava.net.useSystemProxies=true`:

```pwsh
java "-Djava.net.useSystemProxies=true" -jar Komac-1.9.0-all.jar [command]
```

If that works, I can look at always setting that property to true for all builds.

**Comment by CoolPlayLin** [comment]
I want following issue will be resolved with this issue at the same version
- #225

**Comment by russellbanks** [comment]
Please could you test the nightly release to ensure that it works programatically:

```pwsh
komac --use-system-proxy [command]
```

You can also set the environment variable `USE_SYSTEM_PROXY` to `true` if that's easier for you.

**Comment by CoolPlayLin** [comment]
@russellbanks
It's working
<img width="551" alt="image" src="https://github.com/russellbanks/Komac/assets/96709586/9b5e5110-9f35-4e78-b6cc-ecad2a6b18c0">
