### ISSUE TITLE
[Bug]: Wrong RelativeFilePath?

### ISSUE THREAD

**Issue by eitsupi** [russellbanks/Komac#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Thanks for developing this great tool!

I created a PR microsoft/winget-pkgs#113133 with the latest Komac and found that the default `RelativeFilePath` seems wrong.

Currentry: `/foo.exe`
Expected: `foo.exe`

**Comment by russellbanks** [comment]
I've committed a change that removes characters at the start of the relative file path like `./`, `/`, `.\`, `\`

**Comment by eitsupi** [comment]
Thanks for quick updates!
