### ISSUE TITLE
[Bug]: Zip fails to delete

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/96709586/4dd81443-8c3f-43a5-b66e-af828979a0da)

PS: This zip file is over 1GB

**Comment by CoolPlayLin** [comment]
@russellbanks 
It has appeared again

![image](https://github.com/russellbanks/Komac/assets/96709586/6a71486e-a2a0-40b3-9765-0b68dd069c66)

**Comment by CoolPlayLin** [comment]
@russellbanks 
It appears Komac cannot delete this file. IMO, Komac should add mechanism to handle this Exception such as only print some warning to let user know that these cache file should be deleted manually instead of throw such errors.

**Comment by russellbanks** [comment]
I've reported this as an issue to Okio - https://github.com/square/okio/issues/1331

**Comment by russellbanks** [comment]
Fixed in Okio 3.6.0
