### ISSUE TITLE
[Feature/Idea]: Add Support for Manifest 1.5.0

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#276]
### What would you like to see changed/added?

# Reason
- The Manifest 1.5.0 has already published and it appears the validation pipelines has supported for this manifests because https://github.com/microsoft/winget-pkgs/pull/115783 .

# Viable Way
**Komac could provide an option with users so that they could choose it to use newer Manifest Version. And it could still use 1.4.0 version by default.**

**Comment by russellbanks** [comment]
As long as the pipelines accept 1.5.0 manifests, the next version of Komac will support 1.5.0 manifests :)

If you want to specify a specific manifest version you can use the `manifest-version` parameter:
```pwsh
komac up --manifest-version 1.5.0 --id [identifier] --version [version]
```
You can also use `-mv` or `--manifest-override`

**Comment by CoolPlayLin** [comment]
@russellbanks 
- @Trenly has opened a PR in https://github.com/microsoft/winget-pkgs/pull/115783 to update `YamlCreate` to 1.5.0

According to this, I could make sure of is that the pipelines has supported for 1.5.0 when Trenly's PR has merged

**Comment by russellbanks** [comment]
WingetCreate supports 1.5.0 in their [most recent update](https://github.com/microsoft/winget-create/releases/tag/v1.5.1.0), so the pipelines should support it.
