### ISSUE TITLE
[Bug]: Scope is included in portable installers + ARP entries bug

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using the latest nightly JAR, Komac:
- Includes `scope` in portable installers, which is not supported.
- Includes `DisplayName`, `DisplayVersion` in ARP entries, even when they're the same as `PackageName`, `PackageVersion` respectively.
- Includes `NestedInstallerType: portable` and `NestedInstallerFiles.RelativeFilePath: jacktrip.exe` at the global level even when there are other installers with different installers.
- `InstallerLocale: en-US` is present at both installer & global levels.

Created manfiests - https://github.com/microsoft/winget-pkgs/pull/115758/commits/52bc982e3b09317e0f57b06265ed72b43eaf6eb5

I have created the manifest with `new` command and in interactive mode, without using any other parameters.

* Related with: https://github.com/russellbanks/Komac/issues/275

![image](https://github.com/russellbanks/Komac/assets/83997633/54f22d95-f044-44d8-8bcb-228808cb4e6b)

**Comment by CoolPlayLin** [comment]
It appears I cannot skip the option of choosing Scope🤔

**Comment by russellbanks** [comment]
@CoolPlayLin I've added a skip button to the Scope prompt.
