### ISSUE TITLE
[Bug]: The Number of ReleaseNotes' Characters Limit Exceeded

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As the title say, some of publishers and developers would write the ReleaseNotes very detailed. It would cause the number of characters limit exceeded.
Examples:
- https://github.com/microsoft/winget-pkgs/pull/116188/commits/c84516818c623258865af043564ff5a6285fc780
- https://github.com/microsoft/winget-pkgs/pull/116226/commits/c201110c19f8fe9c146813daeda53f2a7d7aaa36
- https://github.com/microsoft/winget-pkgs/pull/116191/commits/4b6e4086b0ffe4ca2ee376df59d6c3495b0fb145

**Comment by russellbanks** [comment]
Hey, this is because the function that cuts release notes to within a character limit hadn't considered line endings, meaning they were going just over the 10,000 character limit.
