### ISSUE TITLE
[Feature/Idea]: Add Validation Manifest

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#281]
### What would you like to see changed/added?

# Reason
Most of low-level errors such as adding Scope in portable manifest would avoid in local validation manifest. But Komac haven't had such feature so it caused Komac would submit mistake manifest to repo. However, Winget-Create have never made such error because it would always validate manifest before every submission.

Some of known issues is also due to this issue
- #280 
- #278 

# Viable Way
I'd like Komac add validation feature like Winget-Create

**Comment by russellbanks** [comment]
If I remember correctly, wingetcreate invokes `winget validate`. This would work but only on Windows. Komac is cross-platform and standalone unlike wingetcreate so this wouldn't be a good fit for Komac.

Komac internally validates manifests to be correct. Bugs slip through like above but I try to fix them when they arise.
