### ISSUE TITLE
[Bug]: URLs are not encoded

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In URLs like `https://desktop-release.canva.com/Canva Setup Latest.exe`, spaces are not replaced with `%20`.

I don't if other special characters are replaced with their URL-encode or not, and have only seen issues with spaces. Please test hat too.

**Comment by russellbanks** [comment]
URLs are intentionally decoded in Komac so they are more readable to the user.

If WinGet sees spaces as not in the same string then I can encode spaces as %20 but validation has passed for https://github.com/microsoft/winget-pkgs/pull/116946 and you can still download the exe if you visit `https://github.com/microsoft/winget-pkgs/pull/116946`.

**Comment by vedantmgoyal2009** [comment]
Sometimes, moderators request changes.

**Comment by russellbanks** [comment]
I've found what you're referring to from Trenly so I'll make the URLs decode but spaces as `%20`.
