### ISSUE TITLE
[Bug]: Unintended Description Formatting

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Another example for ReleaseNotes from <https://github.com/microsoft/winget-pkgs/pull/115107>, where some whitespaces were replaced by another character.

![image](https://github.com/vedantmgoyal2009/vedantmgoyal2009/assets/56779163/7a98fbad-16c0-4814-99d2-9f93856b8d09)

Other examples:
https://github.com/microsoft/winget-pkgs/pull/115665/files
https://github.com/microsoft/winget-pkgs/pull/113559/files

_Originally posted by @SpecterShell in https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1315#issuecomment-1689021893_

**Comment by russellbanks** [comment]
Those release notes from LogSeq seem to contains [non-blocking space characters](https://en.wikipedia.org/wiki/Non-breaking_space). I'll sanitise those in release notes and replace them with regular spaces.
