### ISSUE TITLE
[Feature/Idea]: Signing commits

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#309]
### What would you like to see changed/added?

Add parameters `--key` and `--key-path` which read GPG keys from string and a path to a file containing a key respectively, and use them to create signed commits.

Also, throw error if validate that both flags are passed together.

**Comment by russellbanks** [comment]
rumac will use GitHub's GraphQL API over the REST API. Commits made through the GraphQL API are [automatically signed](https://docs.github.com/en/graphql/reference/mutations#commit-signing) by GitHub.
