### ISSUE TITLE
Rust rewrite

### ISSUE THREAD

**Issue by russellbanks** [russellbanks/Komac#319]
### Summary
I am rewriting Komac in Rust.

### Why are you rewriting Komac in Rust?
I love Kotlin as a language but it suffers from high memory usage and either requires me to bundle the Java Runtime Environment into an installer or have the user already have Java installed and then run a JAR. Kotlin/Native exists but I have to implement logic for each source set where I need to and most Kotlin libraries aren't fully multiplatform yet. Even if Kotlin/Native had a perfect ecosystem, Rust does not have a garbage collector, so there's no overhead there like there is in Kotlin/Native. 

One of the biggest things in Komac currently is reading MSIs etc using native Windows APIs. I have to write lots of Java Native Access code in order to do so.

There's also a lot of things where I've had to implement something from scratch myself where in Rust, there is a crate that does it all for me. E.g. the interactive menus in Komac aren't amazingly versatile. In Rust, I'd use [inquire](https://github.com/mikaelmello/inquire).

### What are the benefits of rewriting Komac in Rust?
- Easier to maintain
- Native executable (e.g. exe for Windows)
- Smaller binary/installer
- Better performance
- **Much** less memory usage

### What does this mean for me?
In the future, you'll have a native executable for your platform and it'll be faster :)
Alongside this, the things that weren't able to be implemented in Komac like secure token storage for Linux and macOS will be in rumac. rumac will also use GitHub's GraphQL API over the REST API which can make getting data from GitHub faster (several REST API calls can be written into one GraphQL query). Additionally, commits created with rumac will be verified as commits created through the GraphQL API are automatically signed by GitHub and marked as verified.

### Progress of Rust rewrite
- [x] New Package command
- [x] Update Command
- [x] Remove Version command
- [x] Cleanup command
- [x] Adding token to platform's secure storage
   - Komac only had this implemented for Windows. rumac has it for all platforms.
- [x] Get values from MSI
   - Komac relied on Msi.dll on Windows or LibMsi on Linux/macOS. rumac uses [rust-msi](https://github.com/mdsteele/rust-msi) to implement this cross-platform.
- [x] Get values from Msix and MsixBundle files
   - [x] Deserialise manifest from XML
   - [x] SignatureSha256
   - [x] [Package Family Name](https://marcinotorowski.com/2021/12/19/calculating-hash-part-of-msix-package-family-name)
- [ ] Get values from ZIP
- [x] Get metadata from GitHub repository from URL
- [x] Interactive menus
- [x] File downloading with progress
- [x] Get architecture of exe
- [x] Check exe is inno, burn, nullsoft, etc
- [x] Version comparison (Knowing which version in a list of versions is the latest one)

**Comment by WoodenMaiden** [comment]
Is there any way to contribute to this Rust rewrite?
