### ISSUE TITLE
[Feature/Idea]: create manifests with version 1.5.0 by default

### ISSUE THREAD

**Issue by soredake** [russellbanks/Komac#333]
### What would you like to see changed/added?

![image](https://github.com/russellbanks/Komac/assets/5204968/63dd211d-b48c-46d1-9a0e-92646c56ab9c)

This version is the default now.

**Comment by russellbanks** [comment]
Since v1.10.0 (released August 16th), Komac supports and creates 1.5.0 manifests by default. Let me know if this isn't the case for you.

**Comment by soredake** [comment]
I realized komac version was stuck at 1.6.0 for some reason, sorry!

**Comment by russellbanks** [comment]
No worries!
