### ISSUE TITLE
[Feature/Idea]: Submit macOS version to Homebrew package manager

### ISSUE THREAD

**Issue by rakleed** [russellbanks/Komac#362]
### What would you like to see changed/added?

Please submit the macOS version of Komac in the Homebrew package manager to make it easier to install and update on macOS/Linux.

Documentation: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by vedantmgoyal2009** [comment]
@russellbanks please update CI to wrap macOS and Linux binaries inside a .tar.gz archive. It is now much easier to publish on brew, since we no longer depend on Java.

**Comment by russellbanks** [comment]
@vedantmgoyal2009 Linux and macOS binaries are now wrapped inside a tar.gz.
