### ISSUE TITLE
[Bug]: Unable to create PR

### ISSUE THREAD

**Issue by teras** [russellbanks/Komac#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I know there is already issue https://github.com/russellbanks/Komac/issues/167 but my results seem completely different (and this thread is closed already, so probably it's irrelevant).

When I run Komac version 1.11.0 (the JAR version under Linux) then every time I try to create a PR, I always get this message:
```Failed to create branch from upstream default branch```

When followed @russellbanks comment [here](https://github.com/russellbanks/Komac/issues/310#issuecomment-1886688939), I downloaded the main branch, compiled Rust version and performed the procedure once more. Then I get another kind of error:
```
Error: 
   0: Failed to create Jubler.App-8.0.0-12207631941812216045
```

For your reference the command I am running is
```
./debug/komac update --identifier Jubler.App --version 8.0.0 --urls https://github.com/teras/Jubler/releases/download/v8.0.0/Jubler-8.0.0.x64.exe
```

It seems that in any case, all of the times, I am not able to create a new PR? 

Thank you for your support.

**Comment by dpprdan** [comment]
@teras Sync your fork https://github.com/teras/winget-pkgs so your `master` branch is up to date with `microsoft/winget-pkgs:master` and `komac update ...` again. Your upstream repo being out of sync with origin is what causes this, I think.

**Comment by teras** [comment]
This is it, indeed!!! Thank you.

I am thinking, is there any way for the use to be informed about this kind of situations? If there were a proper message for this, I wouldn't bother and open an issue. You people have more serious things to do than this.

I consider myself an experienced developer (in the Linux ecosystem), where from time to time I write/update my multi-platform apps. I have only used once `winget` for the original transmission and since I my workspace is Linux, I decided to fight with this tool and try to use it instead.

This tools is awesome, user friendly, and really helped me. But I was lost when a generic error happens.

As a suggestion: even the raw logs to be displayed maybe would have been helpful.

**Comment by soredake** [comment]
> Sync your fork [teras/winget-pkgs](https://github.com/teras/winget-pkgs) so your `master` branch is up to date with `microsoft/winget-pkgs:master` and `komac update ...` again. Your fork being out of sync with ~origin~ upstream is what causes this, I think.

It would be super nice if komac can have option like `--update-master` to do this automatically.

**Comment by russellbanks** [comment]
Thanks for your solution @dpprdan and your feedback @teras and @soredake. This has been a helpful issue for me too because I haven't ever been able to reproduce this because I use [wei/pull](https://github.com/wei/pull) to keep my winget-pkgs fork up-to-date. I'll keep this in mind as it would be good for Komac to have the functionality to update the master branch itself.

**Comment by dpprdan** [comment]
Similar issue with wingetcreate: https://github.com/microsoft/winget-create/issues/502

**Comment by soredake** [comment]
> This has been a helpful issue for me too because I haven't ever been able to reproduce this because I use [wei/pull](https://github.com/wei/pull) to keep my winget-pkgs fork up-to-date.

I didn't know something like this existed, thank you!
