### ISSUE TITLE
[Minor Docs Bug]: Release artifacts still have "nightly" branding

### ISSUE THREAD

**Issue by aaronliu0130** [russellbanks/Komac#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/11874211/b31faae3-eaa2-44d2-86d5-dfc8c4da6162)

**Comment by russellbanks** [comment]
Thanks for spotting - I'll update the release workflow to use the version number instead
