### ISSUE TITLE
[Feature/Idea]: Bootstrap VCRedist dependency for Windows installer

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#411]
### What would you like to see changed/added?

Since Komac is built using the msvc toolchain (the default one) on Windows, the resulting binary now relies on [VCRedist](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) as a dependency. The Windows installer should properly install the dependency if it's not available on the system.

![image](https://github.com/russellbanks/Komac/assets/56180050/4d2c1403-f648-4e5c-89f4-cc70e8d31d15)

**Comment by sitiom** [comment]
- https://github.com/microsoft/winget-pkgs/pull/136918#issuecomment-1913910653

**Comment by russellbanks** [comment]
I've added a step to the Inno installer (using [DomGries/InnoDependencyInstaller](https://github.com/DomGries/InnoDependencyInstaller/)) that checks whether VCRedist is already installed and installs it if it's not.
