### ISSUE TITLE
[Bug]: Output incomplete tag

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Komac v2.0.1 outputs incomplete tag when the tag include "+"

The text that I input
![image](https://github.com/russellbanks/Komac/assets/96709586/207774cd-b5ba-4b8e-a5df-2f6b33d32237)
The text that it output
![image](https://github.com/russellbanks/Komac/assets/96709586/3a386c69-0c55-4eb9-b7f9-fe8d661da62f)

**Comment by russellbanks** [comment]
Fixed in https://github.com/russellbanks/Komac/commit/def1eb5587460e64d23ca11802f7603b61662ce9:

```
> Tags: c++,redist
```
```yaml
Tags:
- c++
- redist
```
