### ISSUE TITLE
[Bug]: Some issue with --identifier

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/46537034/bb86362f-5292-4c20-ac34-0a8b94227307)

**Comment by russellbanks** [comment]
In your second one you missed `komac update` and put `komac --identifier`. You would need to put `komac update --identifier stakira.OpenUTAU.Beta [rest of command]`

**Comment by Exorcism0666** [comment]
Indeed, excuse me for the inconvenience. 😭
