### ISSUE TITLE
[Bug]: ProductCode UUID parsing failed

### ISSUE THREAD

**Issue by Ubujira** [russellbanks/Komac#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When attempting to update `Peppy.Osu!` from `2024.114.0` to `2024.130.2` product code uuid parsing fails due to an invalid character. I am using Komac 2.0.2.

Command:
`komac update -i Peppy.Osu! -v 2024.130.2 -u https://github.com/ppy/osu/releases/download/2024.130.2/install.exe`

Output:
```
Latest version of Peppy.Osu!: 2024.114.0
Error:
   0: ProductCode: UUID parsing failed: invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `o` at 1 at line 16 column 14
```

**Comment by russellbanks** [comment]
Thanks for reporting! This is becuase I assumed all product codes are UUIDs (most are) but Osu's one is `osulazer` which is why it fails to parse as a UUID. I'll change it so that it's just a String.
