### ISSUE TITLE
[Feature/Idea]: Add '-v' as alias for '--version'

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#428]
### What would you like to see changed/added?

I want to input 'Komac -v' to check out version quickly, but Komac has not supported it
![image](https://github.com/russellbanks/Komac/assets/96709586/0f66741f-9995-4059-bb4e-ec89997354b0)

**Comment by Exorcism0666** [comment]
@CoolPlayLin its a "V" and not a "v", so komac -V :)

**Comment by russellbanks** [comment]
https://github.com/russellbanks/Komac/issues/409#issuecomment-1918718296
