### ISSUE TITLE
[Bug]: "called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/46537034/dc0d01f3-5536-47bd-a54d-ab9e7227a33a)
![image](https://github.com/russellbanks/Komac/assets/46537034/605a1d4a-ef9e-47e2-a1e5-fdd46086e153)
All logs: https://github.com/Exorcism0666/AutoPublish/actions/runs/7722685735/job/21051266221

**Comment by russellbanks** [comment]
> Runs normally on physical machine

I've reproduced this issue and I'm working on a fix.

**Comment by CoolPlayLin** [comment]
It produced in v2.0.3 

![image](https://github.com/russellbanks/Komac/assets/96709586/a10e82cc-adf2-4d69-a544-6ff8a595c3cf)

**Comment by aaronliu0130** [comment]
Same here on a physical machine
```sh
~ komac update -i chaiNNer-org.chaiNNer -v 0.21.2 -u https://github.com/chaiNNer-org/chaiNNer/releases/download/v0.21.2/chaiNNer-0.21.2-x64-windows-setup.exe https://github.com/chaiNNer-org/chaiNNer/releases/download/v0.21.2/chaiNNer-windows-x64-0.21.2-portable.zip
Latest version of chaiNNer-org.chaiNNer: 0.20.2
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src\file_analyser.rs:152
```

**Comment by Exorcism0666** [comment]
@russellbanks Other issue with .msi file
![image](https://github.com/russellbanks/Komac/assets/46537034/54135e0a-5af1-4eba-a2ad-54e0e5039b0a)
