### ISSUE TITLE
[Feature/Idea]: Add to package managers

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#43]
### What would you like to see changed/added?

Here's a checklist:
- [x] Winget (https://github.com/microsoft/winget-pkgs/pull/96179)
- [x] Scoop (https://github.com/ScoopInstaller/Extras/pull/10485)
- [ ] Chocolatey (not interested)

**Comment by vedantmgoyal2009** [comment]
I would say that Komac should only be published to WinGet because it is just related to WinGet. Since the other two are competitors of WinGet, we should kind of refrain from publishing on other two.

**Comment by sitiom** [comment]
Should we add the nightly release to Winget?

**Comment by vedantmgoyal2009** [comment]
I don't think since it would be a lot of PRs on winget-pkgs repository. A stable version would be enough for users wanting to contribute to WinGet.

**Comment by russellbanks** [comment]
> Should we add the nightly release to Winget?

I thought about this but really if you're testing Komac, the most ideal thing is to use the Jar from the nightly releases. Reinstalling Komac every day/commit would be unnecessary. The stable release should be enough.

**Comment by sitiom** [comment]
Daily-driving Komac is a form of testing it 😅

**Comment by sitiom** [comment]
> I would say that Komac should only be published to WinGet because it is just related to WinGet. Since the other two are competitors of WinGet, we should kind of refrain from publishing on the other package managers.

We do have [Chocolatey GUI](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Chocolatey/ChocolateyGUI) in Winget though, and [`winget`](https://scoop.sh/#/apps?q=winget&s=0&d=1&o=true) in Scoop. I'd say it would be a form of discovery of other users to Winget.

**Comment by sitiom** [comment]
> For other Linux distros, the JAR can be used.

Or maybe a Flatpak or Snap package?

**Comment by vedantmgoyal2009** [comment]
Well, I did some more research and found out that Homebrew works on both Linux and macOS, so IMO it isn't really needed to publish on `apt` or any Linux package manager.

Take the example of oh-my-posh, it publishes to 3 package managers: Windows (`winget` and `scoop`) and Home`brew`(both Linux and macOS).

**Comment by russellbanks** [comment]
I'd be happy to have Komac added to Chocolatey but ideally someone else managing it would be the best scenario. I'm closing this for now as we have it on most package managers.

**Comment by russellbanks** [comment]
@sitiom The version on Scoop doesn't seem to have been updated since that pull request - are you able update it/provide some insight on how I can automate it?

**Comment by sitiom** [comment]
> @sitiom The version on Scoop doesn't seem to have been updated since that pull request - are you able update it/provide some insight on how I can automate it?

It is updated (https://github.com/ScoopInstaller/Extras/blob/master/bucket/komac.json). The CI is run every 4 hours to auto update every app with the `autoupdate` field.

**Comment by russellbanks** [comment]
Oh perfect - didn't know that's how it worked. Thanks @sitiom

**Comment by sitiom** [comment]
It would be good to add Komac to the [JBang AppStore](https://www.jbang.dev/appstore/) as well
