### ISSUE TITLE
Virus warning for Komac Setup 2.0.3 installer

### ISSUE THREAD

**Issue by ottnorml** [russellbanks/Komac#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi @russellbanks,

I just wanted to let you know about an issue I encountered with Komac version 2.0.3. When I tried to download the installer [`KomacSetup-2.0.3-x64.exe`](https://github.com/russellbanks/Komac/releases/download/v2.0.3/KomacSetup-2.0.3-x64.exe) from the [Github release page for v2.0.3](https://github.com/russellbanks/Komac/releases/tag/v2.0.3), Chrome blocked the download, warning me that the file was detected as a virus.

I checked the file with VirusTotal, and it was indeed detected as a virus by a few antivirus engines. However, it was also detected as safe by the majority of engines.

I'm not sure what's causing this issue, but I thought it would be worth letting you know.

Here's the link to the VirusTotal report:
[Virustotal report link](https://www.virustotal.com/gui/file/2df64c9ba0c28341fe97cf88f3d346beb7360139df59648888b0771f0981d354)

Thanks for your hard work on Komac. It's a great tool!

Best regards

**Comment by russellbanks** [comment]
I've been submitting the KomacSetup installers to Microsoft so that the warnings are removed, although this takes a couple days. I've also got a job that runs on release that submits all releases to VirusTotal, so that they're known pretty quickly.
