### ISSUE TITLE
[Bug]: Apps And Features DisplayVersion not updated

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All logs: https://github.com/microsoft/winget-pkgs/pull/137482

**Comment by russellbanks** [comment]
Komac identifies ARP entries for Inno installers and I aim to look into Nullsoft installers more to achieve the same thing. For plain exe installers that don't follow any structures, it's not possible to retrieve ARP entries and so I would suggest editing the manifest manually using Komac's editor before submitting the pull request.
