### ISSUE TITLE
[Bug]: Malformed FAT (FAT has 3394 entries, but file has only 3392 sectors)

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Works on windows but not on ubuntu (ARM64)

`komac update -i alexx2000.DoubleCommander -v 1.0.11 --urls https://github.com/doublecmd/doublecmd/releases/download/v1.0.11/doublecmd-1.0.11.i386-win32.msi --submit`
![image](https://github.com/russellbanks/Komac/assets/46537034/717047f1-aaa8-4fa5-ad41-15131f0c18dc)

**Comment by russellbanks** [comment]
I haven't been able to reproduce this on Windows or Ubuntu x64. Does this occur repeatedly on Ubuntu ARM64? If so, I can only really report it to the underlying library [mdsteele/rust-msi](https://github.com/mdsteele/rust-msi).

**Comment by Exorcism0666** [comment]
> I haven't been able to reproduce this on Windows or Ubuntu x64. Does this occur repeatedly on Ubuntu ARM64? If so, I can only really report it to the underlying library [mdsteele/rust-msi](https://github.com/mdsteele/rust-msi).

I would like if you can do this :)

**Comment by russellbanks** [comment]
@Exorcism0666, could you check whether this is fixed in Komac [v2.6.0](https://github.com/russellbanks/Komac/releases/tag/v2.6.0) please?
