### ISSUE TITLE
[Feature/Idea]: Publish to crates.io

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#443]
### What would you like to see changed/added?

It would be nice to have a universal way of installing Komac via `cargo install` by publishing it to crates.io. It might also be nice to make it work with [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall) as well ([SUPPORT.md](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md)).

**Comment by vedantmgoyal2009** [comment]
I believe it automatically detects OS and architecture, and I will be able to install Komac using a single command `cargo-binstall` without manually forming URLs and downloading from GitHub.

**Comment by russellbanks** [comment]
Komac is on [crates.io](https://crates.io/crates/komac) now. Cargo-binstall will work in Komac 2.3.0 as the binary names have changed to accomodate what cargo-binstall expects.
