### ISSUE TITLE
[Bug]: No data was returned when parsing values from <repo>

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Not sure what is happening here on my end, I've tried this with both of my Windows and Linux machines with the same result:
```console
> komac update -i vim.vim.nightly -v 9.1.0067 -u https://github.com/vim/vim-win32-installer/releases/download/v9.1.0067/gvim_9.1.0067_x64.exe https://github.com/vim/vim-win32-installer/releases/download/v9.1.0067/gvim_9.1.0067_x86.exe
Latest version of vim.vim.nightly: 9.1.0067
Error:
   0: No data was returned when parsing values from vim/vim-win32-installer
```

**Comment by sitiom** [comment]
Komac v2 requires a new `read:org` scope, didn't notice the update in the README (maybe it should have been in the changelog as part of "breaking changes")

**Comment by russellbanks** [comment]
> Komac v2 requires a new `read:org` scope, didn't notice the update in the README (maybe it should have been in the changelog as part of "breaking changes")

Sorry about that. Vedant pointed this out to me and I intend to get this down to just the `public_repo` to maintain what it was like with Komac v1.

**Comment by sitiom** [comment]
I tried submitting a PR from `komac update` and it created an empty commit. Is this a known bug?
- https://github.com/microsoft/winget-pkgs/pull/137789
