### ISSUE TITLE
[Feature/Idea]: Add '--resolve-issue' optional argument for update/new/remove command

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#449]
### What would you like to see changed/added?

I usually update or add a new manifest according to known issues. But when I open a Pull Request, I have to modify the body manually. I want to use '--resolve-issue' optional argument to link my Pull Request with its issue.

**Comment by russellbanks** [comment]
I've added a parameter to the update, new, and remove command that lets you list issues that would be resolved by the pull request.

Example usage:
```
komac update --identifier Package.Identifier --version 1.2.3 --urls https://example.com --resolves 123 --resolves 456
```
This would then make the pull request body have this:
```
Resolves:
- #123
- #456
```
