### ISSUE TITLE
[Bug]: unmatched InstallerType

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The nightly version's update command changed previous version's `portable` to `exe` caused error
- microsoft/winget-pkgs#138720
- microsoft/winget-pkgs#138721
- microsoft/winget-pkgs#138722
- microsoft/winget-pkgs#138723
- microsoft/winget-pkgs#138724
- microsoft/winget-pkgs#138725
- microsoft/winget-pkgs#138726

**Comment by russellbanks** [comment]
This is because there isn't exactly a way to tell whether the exe is portable or an installer that isn't a known one (like Inno, Nullsoft, etc), so this was treating all portable exe's as the exe installer type. I'll change it so that if the previous installer was portable, it'll use that.

**Comment by stephengillie** [comment]
Could it check the previous manifest version?

**Comment by russellbanks** [comment]
> Could it check the previous manifest version?

That's what https://github.com/russellbanks/Komac/commit/73e31f8d0f4f23801c99a3e8205faae94ed751de (released in Komac 2.0.4) does - if the previous installer's installer type is portable, it will use portable. Otherwise, it will use the installer type Komac has identified.
