### ISSUE TITLE
[Feature/Idea]: Add a command to change the basic text in a PR

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#481]
### What would you like to see changed/added?

For example: I would like a command like `--comment [Automated By Github Actions]` which allow to change this basic text
![image](https://github.com/russellbanks/Komac/assets/46537034/3394bfb5-144a-4919-9580-6dec32ebd115)

**Comment by russellbanks** [comment]
I could add the `KOMAC_CREATED_WITH` and `KOMAC_CREATED_WITH_URL` environment variables as arguments as well?
