### ISSUE TITLE
[Feature/Idea]: automatically open a link to the created PR

### ISSUE THREAD

**Issue by rakleed** [russellbanks/Komac#490]
### What would you like to see changed/added?

It would be nice if the link to the created PR automatically opened in the browser, as is done in wingetcreate.

**Comment by russellbanks** [comment]
I opted against this because creating lots of pull requests in a go could become annoying because lots of tabs will get opened. In the vast majority of terminals, you should be able to click the link that it shown so then the user has the option of whether to open it or not.
