### ISSUE TITLE
[Bug]: MinimumOS and burn

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

* https://github.com/microsoft/winget-pkgs/pull/144004#discussion_r1521753708

**Comment by russellbanks** [comment]
The MinimumOSVersion removal is intentional as lots of manifests have `MinimumOSVersion: 10.0.0.0` and this is unnecessary. The packages that usually have necessary MinimumOSVersions are MSIXs.
