### ISSUE TITLE
[Feature/Idea]: Don't use version numbers in release artifacts

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#52]
### What would you like to see changed/added?

When we use the version in release artifacts, it becomes difficult to download Komac in automated scenarios by using URLs like `https://github.com/russellbanks/Komac/releases/download/latest/Komac-0.9.0.exe`.

* https://github.com/microsoft/winget-cli/issues/2436

**Comment by russellbanks** [comment]
My main thought with this is it would really deter me from being able to make any breaking changes, as all automation would stop working if I published a release that had breaking changes.

Having version numbers does mean you have to manually update them but then you know that it will always work, like dependency updates in a workflow.

**Comment by sitiom** [comment]
You can point to a fixed tag rather than the `latest` tag. That applies to dependencies as well.

**Comment by sitiom** [comment]
Even versioning is inconsistent?
![image](https://user-images.githubusercontent.com/56180050/215364529-6d4e5ebb-786f-42f7-82b1-0525b7a6be3b.png)

**Comment by russellbanks** [comment]
> Even versioning is inconsistent?

macOS distributables can't start with 0's, so that's temporary. It'll be consistent once I have a 1.0.0 release
