### ISSUE TITLE
[Bug]: No release was found with the tag of vX.XXX.X

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
./KomacPortable-linux-x64 update -i eksctl.eksctl -v 0.174.0 -u https://github.com/eksctl-io/eksctl/releases/download/v0.174.0/eksctl_Windows_amd64.zip https://github.com/eksctl-io/eksctl/releases/download/v0.174.0/eksctl_Windows_arm64.zip https://github.com/eksctl-io/eksctl/releases/download/v0.174.0/eksctl_Windows_armv6.zip
```
```
Latest version of eksctl.eksctl: 0.165.0
Error: 
   0: No release was found with the tag of v0.174.0
```

Guessing this is the releasenotes failing to get fetched as the installers go trough, and its saying it cannot find https://github.com/eksctl-io/eksctl/releases/tag/v0.174.0 ?

Edit: seems to work both on Stable and Nightly as of right now..

**Comment by russellbanks** [comment]
https://github.com/russellbanks/Komac/issues/531#issuecomment-2016891817
