### ISSUE TITLE
[Bug]: Invalid zip header

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This bug got found via #531
```
komac update -i fasm.fasm -v 1.73.32 -u https://flatassembler.net/fasmw17330.zip
```

```
Error:
   0: invalid Zip archive: Invalid zip header
```

**Comment by russellbanks** [comment]
This is because the URL is returning error code 400 Bad Request to Komac. I've added a check that the URL is successful so it won't attempt to download it now and instead will say that it returns 400 but I can't figure out why it returns 200 in a browser but not in Komac.

**Comment by OfficialEsco** [comment]
Could there be some user agent magic? IIRC it worked in YamlCreate where we've changed the User Agent

**Comment by russellbanks** [comment]
Doesn't YamlCreate still use `Microsoft-Delivery-Optimization/10.1` like Komac?

https://github.com/microsoft/winget-pkgs/blob/7cb4e5fc300f2ce7927f79c32eb525ad1e28866e/Tools/YamlCreate.ps1#L532

**Comment by OfficialEsco** [comment]
It appears my memory is not on point :D 
Also YamlCreate also fails.. 🤦
```
[Required] Enter the download url to the installer.
Url: https://flatassembler.net/fasmw17330.zip
[Error] Invalid URL Response - The URL did not return a successful response from the server
```

**Comment by russellbanks** [comment]
From the original [pull request](https://github.com/microsoft/winget-pkgs/pull/103807), it looks like it was created manually and wingetbot put Validation-Domain on it, I imagine because it had the same issue of it returning 400. Therefore, I suppose this is the expected behaviour as we want to get the same result as wingetbot.

**Comment by russellbanks** [comment]
https://github.com/russellbanks/Komac/commit/d2be18a2f3fd21c929fbc017643e9d4756609f99 makes the cause of this a lot clearer as it will now say `https://flatassembler.net/fasmw17330.zip returned 400 Bad Request`.
