### ISSUE TITLE
[Feature/Idea]: Edit manifest before creating pull request

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#540]
### What would you like to see changed/added?

I would like to edit my manifest before creating the pull request because sometimes the ARP entries needs to be updated.
It could also be nice to save to disk for easier editing, then use `komac update --manifest` to create a pull request.

**Comment by russellbanks** [comment]
You can save to disk with the `--output` or `-o` parameter. I'll put editing the manifest and submitting manifests from disk to the todo.

**Comment by OfficialEsco** [comment]
Yeee i know, IIRC i tried to edit it but it didn't remember the changes, i also notice the error after running it the first time, which is why i want to postpone the pull request
