### ISSUE TITLE
[Bug]: Installer Switch missing from previous manifest

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've seen this before but didnt think much about it, just saw https://github.com/microsoft/winget-pkgs/pull/146109/files and tested myself, managed to replicate it
```
./KomacPortable-linux-x64 update -i AutoHotkey.AutoHotkey -v 2.0.12 -u https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.12/AutoHotkey_2.0.12_setup.exe
```
(doesn't matter if i paste the same url 4 times)

This is how it should have looked
https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AutoHotkey/AutoHotkey/2.0.11/AutoHotkey.AutoHotkey.installer.yaml

**Comment by russellbanks** [comment]
Thanks for reporting! I hadn't considered that you could have partial installer switches at root and then different installer switches at installer level, like a global silent switch then individual custom switches, for example. Are there any others this would be applicable to?
