### ISSUE TITLE
[Bug]: Installer Locale?

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

"Locale" seems to be missing in this prompt:
![image](https://user-images.githubusercontent.com/56180050/215364199-b962e6f9-30e4-4e04-b7ae-91a6703eeccf.png)

**Comment by russellbanks** [comment]
@allcontributors please add @sitiom for bug
