### ISSUE TITLE
[Bug]: komac omits `MinimumOSVersion` from previous manifest

### ISSUE THREAD

**Issue by soredake** [russellbanks/Komac#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've done `komac update --identifier Digimezzo.Dopamine.3 --version 3.0.0-preview.25 --urls https://github.com/digimezzo/dopamine/releases/download/v3.0.0-preview.25/Dopamine-3.0.0-preview.25.exe`

Previous manifest have this line https://github.com/soredake/winget-pkgs/blob/master/manifests/d/Digimezzo/Dopamine/3/3.0.0-preview.14/Digimezzo.Dopamine.3.installer.yaml#L6

But the updated manifest is not:
![image](https://github.com/russellbanks/Komac/assets/5204968/f7d185d8-bcdc-4ec6-9671-04680d5893da)

**Comment by russellbanks** [comment]
The removal of `MinimumOSVersion: 10.0.0.0` is intentional - https://github.com/russellbanks/Komac/issues/514#issuecomment-1992283735
