### ISSUE TITLE
[Bug]: Error when trying to update an existing package to a new version 

### ISSUE THREAD

**Issue by jahvari** [russellbanks/Komac#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I attempted to create a new version for naps2, this is the error I received from CMD. 
![Capture](https://github.com/russellbanks/Komac/assets/75337667/f0afa489-6bdc-45a9-a85f-3212da42e9fb)

**Comment by jahvari** [comment]
I am not sure about the error but it looks like the package already has the new version

**Comment by russellbanks** [comment]
Were you using a classic or fine-grained token?

**Comment by jahvari** [comment]
@russellbanks This was a classic token.

**Comment by russellbanks** [comment]
I believe this is because your [winget-pkgs fork](https://github.com/jahvari/winget-pkgs) has committed changes to main and isn't up-to-date with master. I'd suggest re-creating the fork.
