### ISSUE TITLE
[Bug]: Unicode symbols incorrectly parsed

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My input for `Copyright`:  `Copyright © 2022`
What was written to the manifest: `Copyright \0 2022`
![image](https://user-images.githubusercontent.com/56180050/215531948-8b1f23db-894d-4dfb-acac-c1977cdd90fe.png)

**Comment by russellbanks** [comment]
I've looked into this a lot and it's down to the encoding that Java/Windows is using by default. It works as expected for me in the IntelliJ Idea terminal but not when running the Shadow Jar/anything else in Windows Terminal. I've tried running with `-Dfile.encoding=UTF-8` too and that doesn't seem to help, so I'm a bit stuck currently.

**Comment by vedantmgoyal2009** [comment]
How about `UTF-16`?

**Comment by SpecterShell** [comment]
> I've tried running with `-Dfile.encoding=UTF-8` too and that doesn't seem to help

This parameter only sets the input/output encoding of Java programs to UTF-8, while the encoding of the console isn't.

You can try `chcp 65001` in cmd and
```PowerShell
[System.Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding(65001)
[System.Console]::InputEncoding = [System.Text.Encoding]::GetEncoding(65001)
```
in PowerShell to also set the encoding for the console.

**Comment by SpecterShell** [comment]
BTW You can see current code page in the conhost "Properties" window:
![image](https://github.com/russellbanks/Komac/assets/56779163/51d56d0e-0456-4d9c-aa94-d977031d74cf)
