### ISSUE TITLE
[Bug]: `komac update` removes `AppsAndFeaturesEntries` in `Installers`

### ISSUE THREAD

**Issue by rakleed** [russellbanks/Komac#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```shell
komac update -u https://download.gigabyte.com/FileList/Utility/GCC_24.05.01.01.zip -i GIGABYTE.GigabyteControlCenter -v 24.05.01.01
```

`AppsAndFeaturesEntries` should remain the same as in the [previous version](https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/GIGABYTE/GigabyteControlCenter/24.03.29.01/GIGABYTE.GigabyteControlCenter.installer.yaml#L18-L21), but komac simply removes this property.

**Comment by OpenWaygate** [comment]
It also removes `Commands` field from `.installer.yaml`.

I missed `Commands` field when I `komac new`, but I add it manually in a pr([release 0.8.5](https://github.com/microsoft/winget-pkgs/pull/157129/files)).

However, in my pr of [release 0.9.0](https://github.com/microsoft/winget-pkgs/pull/157958/files), the `Commands` field disappears.

I use vedantmgoyal2009/winget-releaser@v2.

**Comment by russellbanks** [comment]
> I use [vedantmgoyal2009/winget-releaser@v2](https://github.com/vedantmgoyal2009/winget-releaser).

WinGet Releaser currently uses Komac v1. WinGet Releaser will update to Komac v2 when Komac v2.3.0 is released.

**Comment by russellbanks** [comment]
`AppsAndFeaturesEntries` should not remain the same as in a previous version by default. `DisplayVersion` can often change between releases and keeping one for a previous version can cause incorrect matching. Where it can, Komac will identify ARP entries for a given installer. In very specific edge cases, I would suggest manually editing the manifest in Komac's editor.
