### ISSUE TITLE
[Bug]: Crashes when these specific URLs are used

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

These are the URLs:
https://files.progdvb.com/progtv_win/ProgTV3.2.6.0.x86.msix
https://files.progdvb.com/progtv_win/ProgTV3.2.6.0.x64.msix

![image](https://github.com/russellbanks/Komac/assets/81376423/3dfe2be0-e64a-4208-8d4d-bccd414594f0)

**Comment by russellbanks** [comment]
Thanks for reporting! I've covered the case of multiple [`TargetDeviceFamily`](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-targetdevicefamily) elements in the MSIX manifest.
