### ISSUE TITLE
[Bug]: The installer type is unexpectedly changed to portable

### ISSUE THREAD

**Issue by SpecterShell** [russellbanks/Komac#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For some inexplicable reasons, the installer type may be changed to `portable`, e.g.,
- https://github.com/microsoft/winget-pkgs/pull/158983/files#diff-44dbafb0bfd0561b606b2f808dc2b7d0431fa679432c52b4db8a6bffe358b292R6
- https://github.com/microsoft/winget-pkgs/pull/152095/files#diff-3c79a25cb9eb2d13da1a10cce020b61423a38f92ac03d501a52adbdd903ac7f6R6

**Comment by russellbanks** [comment]
This is fixed in the next Komac update (2.3.0). I'll make an release for this soon.
