### ISSUE TITLE
[Bug]: `PortableCommandAlias` should be omitted if left empty

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/56180050/72374ea6-b0d0-4d0e-9465-b7bb621fa948)

![image](https://github.com/russellbanks/Komac/assets/56180050/8f5d2c56-35b3-4bcf-83a4-0df02c8b856b)

**Comment by russellbanks** [comment]
Thanks for reporting!
