### ISSUE TITLE
[Bug]: No release was found with tag of download

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hiya, just got this error, anyway this could be fixed or bypassed?

![image](https://github.com/russellbanks/Komac/assets/81376423/bca83b7b-ca04-4df4-9007-4832a71f46e9)

**Comment by vedantmgoyal9** [comment]
Try using https://github.com/Vencord/Installer/releases/download/v1.4.0/VencordInstallerCli.exe

**Comment by vikingnope** [comment]
Weirdly enough that works, but I would prefer not to use that link since it says 1.4.0

**Comment by vedantmgoyal9** [comment]
Winget prefers to use a versioned URL, not a permanent URL which always redirects to the latest release. It breaks manifests with "installer sha256 hash mismatch" and users are explicitly required to override the error.

**Comment by vikingnope** [comment]
Yep I fully agree with you on this and I understand it, but the thing is with the other link, we will get the same issue anyways, for some reason it acts also as a  "latest version" link (Don't know why projects do this), so it isn't an issue with Komac really and truly. I thank you for your continuous support anyways :)

**Comment by russellbanks** [comment]
I could possibly make it so that if you give komac the 'latest' link it will turn it into a versioned link.

**Comment by russellbanks** [comment]
> I could possibly make it so that if you give komac the 'latest' link it will turn it into a versioned link.

Going to `https://github.com/Vencord/Installer/releases/latest/download/VencordInstallerCli.exe` actually redirects to `https://github.com/Vencord/Installer/releases/download/v1.4.0/VencordInstallerCli.exe` so if the url has `latest/download`, I would just need to follow the redirect by one hop.
