### ISSUE TITLE
[Bug]: Cargo install issues

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Was trying to install using cargo on Arch Linux and this happened:

![image](https://github.com/russellbanks/Komac/assets/81376423/6237fde3-6bce-4632-aa0f-85278706e80a)

![image](https://github.com/russellbanks/Komac/assets/81376423/f1c57ad1-ed1e-4e23-b2bb-feb83927ad24)

**Comment by vikingnope** [comment]
cargo binstall worked fine, should I leave this open or close it?

**Comment by russellbanks** [comment]
This should be resolved in the next version of Komac. It appears to be because tui-textarea had an issue where it was picking up the wrong version of ratatui but has since been [resolved](https://github.com/rhysd/tui-textarea/pull/69) and updated.

**Comment by joshka** [comment]
Consider adding `--locked` to the cargo install instructions to help avoid this problem in future.
