### ISSUE TITLE
[Feature/Idea]: Allow option to link a GitHub Issue

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#674]
### What would you like to see changed/added?

Give us the option to set a GitHub Issues link (can be left empty if no issue is linked, sort of same concept with URL installer links) and this should create the template on the GitHub PR as follows:

```
Pull request has been created with komac v....

Resolves: <GitHub Issues link>
```

**Comment by russellbanks** [comment]
This already exists with `--resolves` - https://github.com/russellbanks/Komac/issues/449#issuecomment-1927306920
