### ISSUE TITLE
[Bug]: Arch Linux not saving GH token

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi again,

I have an issue where after installing using `cargo-binstall` and adding cargo to my environment variables in Arch Linux, it seems like it is never saving the GitHub token and keeps asking me for it each time. Any help would be appreciated.

**Comment by vikingnope** [comment]
Solved by installing `gnome-keyring`

**Comment by russellbanks** [comment]
Thanks for letting me know. I'll add this to the ReadMe.
