### ISSUE TITLE
Support WinGet 1.9 manifests

### ISSUE THREAD

**Issue by russellbanks** [russellbanks/Komac#745]
This issue is a tracker for winget schema 1.9. This will be a very easy addition but will wait until 1.9 schemas are accepted into winget-pkgs.

- https://github.com/microsoft/winget-pkgs/issues/186398
- https://github.com/microsoft/winget-pkgs/issues/165726
- https://github.com/microsoft/winget-pkgs/pull/165728

**Comment by Dragon1573** [comment]
According to the [pull request template](https://github.com/microsoft/winget-pkgs/blob/master/.github/PULL_REQUEST_TEMPLATE.md), _WinGet_ team now prefer manifest version `1.9.0` instead of previous `1.6.0`. Commits of this modification is performed at `Dec 4, 2024, 1:00 AM GMT+8` (14 hours ago) by **Trenly**, with SHA microsoft/winget-pkgs@88f8f01 .

**Comment by sitiom** [comment]
From the closed PRs:
> Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

Support for `ArchiveBinariesDependOnPath` would be nice 🙂

**Comment by jo-chemla** [comment]
Wow that was fast, thanks for adding support for `ArchiveBinariesDependOnPath`!

**Comment by russellbanks** [comment]
> Subscribing to this thread to get notified about Komac next update - looks like the latest [Release Github Action](https://github.com/russellbanks/Komac/actions/runs/12174439234) have not pushed 2.8.0 to github, winget etc, probably because it requires a manual trigger

I'll be releasing komac 2.8.0 tomorrow!
