### ISSUE TITLE
[Feature/Idea]: ability to skip "No release was found with the tag of release" error

### ISSUE THREAD

**Issue by soredake** [russellbanks/Komac#767]
### What would you like to see changed/added?

I am trying to create pr for FxSoundLLC.FxSound with `komac update FxSoundLLC.FxSound -o . --version 1.1.26.0 --urls https://github.com/fxsound2/fxsound-app/raw/14145b12e8da6ef6e381649ca0fab23584043eff/release/fxsound_setup.exe` command, and it fails with:
```
Latest version of FxSoundLLC.FxSound: 1.1.16.0
Error:
   0: No release was found with the tag of release
```

That's because they tag latest version as "latest" instead of number in github releases https://github.com/fxsound2/fxsound-app/releases

**Comment by russellbanks** [comment]
This is a very specific way of doing release but I've changed it to just ignore it if there isn't an associated release it can find based on the URL.
