### ISSUE TITLE
[Feature/Idea]: `cleanup` - get all associated pull requests within one request

### ISSUE THREAD

**Issue by stevenlele** [russellbanks/Komac#778]
### What would you like to see changed/added?

Currently, `cleanup` command sends one API request per branch:

https://github.com/russellbanks/Komac/blob/5ab284a0ec14adce6a4652ab36e7ae4902150b8e/src/commands/cleanup.rs#L67-L78

Actually you can get the information within the get-branches request:

https://github.com/russellbanks/Komac/blob/5ab284a0ec14adce6a4652ab36e7ae4902150b8e/src/commands/cleanup.rs#L46-L48

Here's an example of the GraphQL query:

```diff
 query GetBranches($owner: String!, $name: String!) {
   repository(name: $name, owner: $owner) {
     id
     defaultBranchRef {
       name
       id
     }
     refs(first: 100, refPrefix: "refs/heads/") {
       nodes {
         name
+        associatedPullRequests(
+          first: 5,  # fetch some more in case user opened PR against their own repo, or opened a new PR because previous one is closed
+        ) {
+          nodes {
+            title
+            url
+            state
+            repository {
+              nameWithOwner  # filter this by "microsoft/winget-pkgs"
+            }
+          }
+        }
       }
     }
   }
 }
```

~~You can pass the wanted `states` as a variable (as long as people don't re-open PRs with the same branch), or just check the `state` property in the result like how it's currently done.~~ Edit: You should keep the current behavior. Filtering it in the query might cause false positives when the user opens a new PR when the previous one is closed unmerged.

To be safe, you should also fetch more than 1 PR per branch and filter `repository.name_with_owner` by `microsoft/winget-pkgs`. I sometimes mistakenly open pull requests again my own fork repo, especially when it's made through the web UI, and I think other people sometimes do this too. If we use `first: 1`, we might never get the correct PR against the `microsoft` repo. (Edit: it might make sense to make sure PRs against other repos are closed/merged too)

In fact this also fixes a bug caused by fetching PR by branch name instead of branch ID. I once reused a deleted branch name when manually creating a PR to modify a manifest I created, but Komac thinks this branch is merged and listed it in `cleanup`. By fetching `associatedPullRequests`, this issue is resolved automatically.

**Comment by russellbanks** [comment]
This was a brilliant issue, thank you!
