### ISSUE TITLE
[Feature/Idea]: Allow to set custom commit user and email

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#78]
### What would you like to see changed/added?

https://docs.github.com/en/rest/git/commits?apiVersion=2022-11-28#create-a-commit

The GitHub REST API allows setting custom commit names and emails. GitHub Codespaces use `$GIT_COMMITTER_NAME` and `$GIT_COMMITTER_EMAIL` environment variables.

![image](https://user-images.githubusercontent.com/83997633/218007130-c14cefd9-433c-4e01-9955-4d31cf07e95b.png)

So, if **both** of the above variables are set in the environment, we can add their value to the REST API request, else, use omit them so that the API will use the default name & email associated with the GitHub token supplied.

**Comment by russellbanks** [comment]
This was implemented in https://github.com/russellbanks/Komac/commit/7bcb793141432d63bea2edfe92bab9e1fbbfb4b4 and https://github.com/russellbanks/Komac/pull/67
