### ISSUE TITLE
[Bug]: Using v2.8.0 creates duplicate for arm64

### ISSUE THREAD

**Issue by arturcic** [russellbanks/Komac#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It seems version v.2.8.0 add a duplicate for arm64

When I was publishing version 6.1.0 of GitVersion using this command:

```bash
komac update GitTools.GitVersion --version 6.1.0 --urls https://github.com/GitTools/GitVersion/releases/download/6.1.0/gitversion-win-x64-6.1.0.zip https://github.com/GitTools/GitVersion/releases/download/6.1.0/gitversion-win-arm64-6.1.0.zip --token *** --submit
```

It seems the generated version contains 3 installers, 2 of them are duplicates. See the commit

https://github.com/microsoft/winget-pkgs/commit/77dc3548f4f4ae01a3332a60542d49843a997225

I had to manually fix the manifest

**Comment by russellbanks** [comment]
Thanks for reporting! :)
