### ISSUE TITLE
[Feature/Idea]: Support for multiple aliases in a single executable

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#96]
### What would you like to see changed/added?

Related issues:
- https://github.com/microsoft/winget-cli/issues/2884
- https://github.com/microsoft/winget-cli/issues/2887

See [flyctl](https://github.com/microsoft/winget-pkgs/blob/def91481aa44bed09c1ecac3e44e6a95cc430cf2/manifests/f/Fly-io/flyctl/0.0.450/Fly-io.flyctl.installer.yaml#L12-L15). Normally, duplicate `RelativeFilePath`s don't get validated successfully, but has a workaround, allowing for multiple aliases in a single executable. In Komac, it seems like I can only add 1 alias per executable. Please add support for this use case, thanks!

**Comment by sitiom** [comment]
It seems like this works just fine by skipping the prompt via the `--urls` flag, but it would be nice to be able to do this interactively.

**Comment by russellbanks** [comment]
With this workaround does this mean that there can only be up to two aliases (`program.exe` and `./program.exe`)? If so, that just means adding an extra prompt for the second one (but specifying that it's a workaround and unless it's needed, one should suffice)

**Comment by sitiom** [comment]
> With this workaround does this mean that there can only be up to two aliases (`program.exe` and `./program.exe`)?

Maybe something like `.\program.exe` or `./././` will work too, allowing for unlimited aliases 🙂

**Comment by russellbanks** [comment]
Do those work for sure?

**Comment by russellbanks** [comment]
One consideration is that https://github.com/microsoft/winget-cli/issues/2887 treats the functionality as a bug at the moment, meaning the manifest created would be invalid in the future.

**Comment by sitiom** [comment]
So would they remove manifests in the repo currently using the "bug?" At least they should provide a proper solution for multiple aliases before they fix it.

**Comment by russellbanks** [comment]
I'm going to close this as not planned as WinGet doesn't have functionality for mutliple aliases and https://github.com/microsoft/winget-cli/issues/2887 treats using `./` as a bug. I'm happy to re-open this and add the functionality if https://github.com/microsoft/winget-cli/issues/2884 gets accepted and implemented.
